name: SecurityPipeline

on: [push]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with: # Required when commit authors is enabled
        fetch-depth: 0
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Trivy vulnerability scanner FS
        uses: aquasecurity/trivy-action@master
        with:
          # optional, default is image, but can be conf and fs
          scan-type: 'fs'
          #default table, but can be sarif
          format: 'table'
          # Save file?
          # output: 'trivy-results.sarif'
          # Break the Pipeline? 1 = yes, 0 = no
          exit-code: '0' 
          # ignore unfixed vulnerabilities
          ignore-unfixed: true
          vuln-type: 'os,library'
          # optional, default is UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          severity: 'MEDIUM,HIGH,CRITICAL'
